### ISSUE TITLE
Redmine 2.4.2 unsupported

### ISSUE THREAD

**Issue by condemil** [kato-im/redmine_kato#4]
redmine_kato plugin is not working with Redmine 2.4.2 that comes as a package for Ubuntu 14.04 LTS.

**Comment by JLarky** [comment]
@condemil thanks for notifying us about that!
I just commited 4b563b6346b1e325038d7a9753888435b01968e5 and it seem to work on my ubuntu 13.10 with redmine 2.4.2, so I hope it helps

**Comment by condemil** [comment]
It works fine now, thanks!
